apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyweb
spec:
  replicas: { { .Values.replicas } }
  selector:
    matchLabels:
      app: tinyweb
  template:
    metadata:
      labels:
        app: tinyweb
    spec:
      containers:
        - name: tinyweb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
